# Generated by Django 3.2.6 on 2021-08-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_numer',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_adress2',
            new_name='street_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_adress1',
        ),
        migrations.AddField(
            model_name='order',
            name='street_address1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
